### ISSUE TITLE
esp now location monitor

### ISSUE THREAD

**Issue by zhjygit** [Vyas-M/ESP-NOW-Firebase#1]
I have two esp device, esp  device commucates via nearby ap.
esp device has gps module and lcd dispaly.
how can dispaly location itself and location another device or others device nearby, and lcd dispaly shows the locations on the maps with refresh every some seconds.

To finish my idea, is it necessary to use firebase?
All of datas or device are only between esp devices and ap, no phone , no pc.

**Comment by Vyas-M** [comment]
I am unable to clearly understand your query, however, based on my understanding, if only the location info from the GPS module has to be transmitted between a couple of ESP 32 devices that are interconnected, then Firebase is not required in my opinion, as you don't have any desktop or mobile application involved. As far as the location displayed on the maps, it depends on the GPS module being used.
